#!/bin/bash

if [ $# -lt 4 ]; then
  echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
  exit 1
fi

path_to_file=$1
ip=$2
username=$3
ssh_key=$4

echo "some_page.html $path_to_file to server $ip..."

scp -o "StrictHostKeyChecking no" -i "$ssh_key" "$path_to_file" "$username@$ip:~/" 

echo "some_page.html successfully." 
